version: '2'
services:
  database:
    build: db
    restart: always
    environment:
      POSTGRES_DB: ${{ env.ZAO_CHAT_DB }}
      POSTGRES_PASSWORD: ${{ secrets.REST_DB_SECRET }}
  app:
    build: app
    depends_on: [database]
    links:
      - database
    ports:
      - "5000:5000"
    environment:
      SQLALCHEMY_DATABASE_URI: ${{ env.ZAO_CHAT_DB }}
